/* eslint-disable no-unused-expressions */
/* eslint-disable no-unused-vars */
/* eslint-disable jsx-a11y/anchor-is-valid */
/* eslint-disable jsx-a11y/img-redundant-alt */
/* eslint-disable no-mixed-spaces-and-tabs */
/* eslint-disable no-tabs */
/* eslint-disable no-undef */
/* eslint-disable jsx-a11y/control-has-associated-label */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Pagination, Navigation } from 'swiper';
import styles from '../styles/Landing.module.css';
import imgSection1 from '../public/images/section1Landing.jpg';
import imgSection2 from '../public/images/section2Landing.jpg';
import imgSection3 from '../public/images/section3Landing.jpg';
import Bluecheckbox from '../public/icon/bluecheckbox.svg';
import Yellowcheckbox from '../public/icon/yellowcheckbox.svg';
import Navbar from '../components/navbarLanding';
import styleFooter from '../styles/Footer.module.css';
import LogoFooter from '../public/logo.svg';
import UserOpini from '../public/images/useropinion.jpg';
import UserOpini2 from '../public/images/useropinion2.jpg';
import UserOpini3 from '../public/images/useropinion3.jpg';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';

function Landingpage() {
  return (
    <>
      <Head>
        <title>Landingpage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={`container-fluid ${styles.container}`}>
        <div className={`row ${styles}`}>
          <section className={`row ${styles.section1}`}>
            <div className="col-1" />
            {/* ---------Left---------- */}
            <div className={`col-5 ${styles.divLeft1}`}>
              <div className={`row ${styles.mainLeft1}`}>
                <div className={styles.title1}>
                  <h3>Talenta terbaik negri untuk perubahan revolusi 4.0</h3>
                </div>
                <div className={styles.loream1}>
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui,
                  consequuntur, alias debitis nisi fuga voluptas.
                </div>
                <div className={`${styles}`}>
                  <Link href="/home">
                    <button className={styles.buttonSearch}>
                      <div>Mulai Dari Sekarang</div>
                    </button>
                  </Link>
                </div>
              </div>
            </div>
            {/* -----------------Right--------------- */}
            <div className={`col-5 ${styles.divRight1}`}>
              <div className={styles.mainRigh1}>
                <div className={styles.background1} />
                <div className={styles.divImage1}>
                  <Image
                    className={styles.image1}
                    src={imgSection1}
                    width={500}
                    height={430}
                  />
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section2------------------------ */}
          <section className={`row ${styles.section2}`}>
            <div className="col-1" />
            {/* -------left------ */}
            <div className={`col-5 ${styles.section2Responsive}`}>
              <div className={styles.mainRigh1}>
                {/* <div className={styles.divSquare}></div> */}
                <div className={styles.background2} />
                <div className={styles.divImage2}>
                  <Image
                    className={styles.image2}
                    src={imgSection2}
                    width={400}
                    height={320}
                  />
                </div>
              </div>
            </div>

            {/* ------Right------- */}
            <div className={`col-5 ${styles.divLeft1}`}>
              <div className="row">
                <div className={styles.title2}>
                  <h3>Kenapa harus mencari tallent di peworld</h3>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image
                      className={styles}
                      src={Bluecheckbox}
                      width={15}
                      height={15}
                    />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image
                      className={styles}
                      src={Bluecheckbox}
                      width={15}
                      height={15}
                    />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image
                      className={styles}
                      src={Bluecheckbox}
                      width={15}
                      height={15}
                    />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
                <div className={styles.divList1}>
                  <div className={styles.checklist1}>
                    <Image
                      className={styles}
                      src={Bluecheckbox}
                      width={15}
                      height={15}
                    />
                  </div>
                  <div>Lorem ipsum dolor sit amet.</div>
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section3------------------------ */}
          <section className={`row ${styles.section3}`}>
            <div className="col-1" />
            {/* -------left------ */}
            <div className={`col-5 ${styles.leftContent3}`}>
              <div className={styles.divTitle3}>
                <h3>Skill Tallent</h3>
              </div>
              <div className={styles.divLorem}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
                euismod ipsum et dui rhoncus auctor.
              </div>
              <div className={styles.divList3}>
                <div style={{ marginRight: '100px' }}>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>Java</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>Kotlin</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>PHP</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>Javascript</div>
                  </div>
                </div>
                <div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>Golang</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>C++</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>Ruby</div>
                  </div>
                  <div className={styles.divList1}>
                    <div className={styles.checklist1}>
                      <Image
                        className={styles}
                        src={Yellowcheckbox}
                        width={15}
                        height={15}
                      />
                    </div>
                    <div>10+ Bahasa Lainnya</div>
                  </div>
                </div>
              </div>
            </div>

            {/* ------Right------- */}
            <div className={`col-5 ${styles.section3Responsive}`}>
              <div className={styles.mainRigh1}>
                {/* <div className={styles.divSquare}></div> */}
                <div className={styles.background3} />
                <div className={styles.divImage3}>
                  <Image
                    className={styles.image3}
                    src={imgSection3}
                    width={470}
                    height={330}
                  />
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section4------------------------ */}
          <section className={`row ${styles.section4}`}>
            <div className="col-1" />
            {/* -------main------ */}
            <div className="col-10">
              <div className={styles.title4}>
                <h3>Their opinion about peworld</h3>
              </div>
              <div className={styles.divCardUser}>
                <Swiper
                  slidesPerView={3}
                  spaceBetween={30}
                  slidesPerGroup={3}
                  loop
                  loopFillGroupWithBlank
                  pagination={{
                    clickable: true,
                  }}
                  navigation
                  modules={[Pagination, Navigation]}
                  className="mySwiper"
                >
                  <SwiperSlide>
                    <div className={`card d-flex align-items-center ${styles.responsiveCardSwiper}`} style={{ width: '18rem' }}>
                      <div style={{ marginTop: '10%' }}>
                        <Image src={UserOpini} width={100} height={100} style={{ borderRadius: '100%' }} />
                      </div>
                      <div className="card-body d-flex flex-column align-items-center">
                        <h5 className="card-title">Harry Styles</h5>
                        <h6 style={{ color: '#9EA0A5' }}>Web Developer</h6>
                        <p className="card-text" style={{ marginLeft: '10%' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.</p>
                      </div>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className={`card d-flex align-items-center ${styles.responsiveCardSwiper}`} style={{ width: '18rem' }}>
                      <div style={{ marginTop: '10%' }}>
                        <Image src={UserOpini2} width={100} height={100} style={{ borderRadius: '100%' }} />
                      </div>
                      <div className="card-body d-flex flex-column align-items-center">
                        <h5 className="card-title">Niall Horan</h5>
                        <h6 style={{ color: '#9EA0A5' }}>Web Developer</h6>
                        <p className="card-text" style={{ marginLeft: '10%' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.</p>
                      </div>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className={`card d-flex align-items-center ${styles.responsiveCardSwiper}`} style={{ width: '18rem' }}>
                      <div style={{ marginTop: '10%' }}>
                        <Image src={UserOpini3} width={100} height={100} style={{ borderRadius: '100%' }} />
                      </div>
                      <div className="card-body d-flex flex-column align-items-center">
                        <h5 className="card-title">Louis Tomlinson</h5>
                        <h6 style={{ color: '#9EA0A5' }}>Web Developer</h6>
                        <p className="card-text" style={{ marginLeft: '10%' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor.</p>
                      </div>
                    </div>
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
            <div className="col-1" />
          </section>

          {/* ------------------section------------------------ */}
          <section className="row">
            <div className="col-1" />
            <div className="col-10">
              <div
                style={{
                  backgroundColor: '#5E50A1', minHeight: '200px', paddingTop: '6%', borderTopLeftRadius: '50px', borderBottomLeftRadius: '5px', borderBottomRightRadius: '50px', borderTopRightRadius: '5px', marginTop: '50px',
                }}
                className="container"
              >
                <div className={styles.invitation}>
                  <div className="d-block d-md-flex justify-content-between">
                    <h3 style={{ maxWidth: '300px', color: 'white' }}>Lorem ipsum dolor sit amet.</h3>
                    <br />
                    <div className="d-flex align-items-center">
                      <button className="btn bg-light py-3">Mulai Dari Sekarang</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-1" />
          </section>
        </div>

      </div>
      <div className={styles.responsiveFooter} style={{ marginTop: '290px' }}>
        <footer className={`${styleFooter.footer}`}>
          <div className={`d-flex flex-column align-items-center h-100 ${styleFooter.footerMargin}`}>
            <div className="w-100 d-flex flex-column justify-content-left align-items-start">
              <Image
                className={styles.image1}
                src={LogoFooter}
                width={200}
                height={50}
              />
            </div>
            <div className={`w-100 d-flex ${styleFooter.textFooter}`}>
              <small className={styleFooter.footerH1}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod ipsum et dui rhoncus auctor</small>
            </div>
            <div className={`d-flex ${styleFooter.footerBottom} justify-content-left align-items-start`}>
              <div>2020 Pewworld. All right reserved</div>
              <div className={`d-flex justify-content-end ${styleFooter.contact}`}>
                <div className={styleFooter.phone}>Telepon</div>
                <div className={styleFooter.email}>Email</div>
              </div>

            </div>
          </div>
        </footer>
      </div>
    </>
  );
}

export default Landingpage;
